name: 'Dev Container CI'
description: 'Publish custom development container feature(s) and/or templates(s)'
author: 'GitHub'
branding:
  icon: box
  color: blue
inputs:
  # Global options
  publish-features:
    required: false
    default: "false"
    description: "['true'/'false'] Publish dev container 'feature' artifacts"
  publish-templates:
    required: false
    default: "false"
    description: "['true'/'false'] Publish dev container 'template' artifacts"

  # 'features' options
  base-path-to-features:
    required: false
    default: './features/src'
    description: "Relative path to the 'src' folder containing dev container 'feature(s)'"

  # 'template' options
  base-path-to-templates:
    required: false
    default: './templates/src'
    description: "Relative path to the folder containing dev container 'template(s)'"

runs:
  using: 'node12'
  main: 'dist/index.js'
