name: "Test Scenarios"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scenarios:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'no-ci') && !contains(github.event.head_commit.message, 'CI ignore')"
    steps:
      - uses: actions/checkout@v2
      - name: " Running predefined test scenarios"
        run: npx --yes ./devcontainers-cli-0.3.0.tgz features test --scenarios `pwd`/test-scenarios -c `pwd`
