name: "Test Scenarios"
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scenarios:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Running predefined test scenarios"
        run: devcontainer features test --scenarios `pwd`/test-scenarios -c `pwd`
